### ISSUE TITLE
data disappeared

### ISSUE THREAD

**Issue by iamxujian** [AzurLaneTools/AzurLaneData#1]
data in some files disappeared. such as:

[buffCfg.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/CN/buffCfg.json)
[skillCfg.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/CN/skillCfg.json)

did some error occurred during converting lua to json?

**Comment by AutumnSun1996** [comment]
It's caused by https://github.com/K0lb3/UnityPy/issues/112

Original issue is already solved, and the data should come back soon

**Comment by iamxujian** [comment]
UnityPy, seems like a powerful lib, interesting. luckily to know a new lib. 
i'm expecting data's recurrence. Thank you very much.

**Comment by iamxujian** [comment]
the data files are still empty, so i re-opened this one

**Comment by AutumnSun1996** [comment]
Another issue comes from the lua code change.
Fixed in aba8350082297c99a574a0333b6caec744db79ad ~ 12c042ff79bd0dd402d24e381be98c9afe80e45c
