### ISSUE TITLE
5月9号国服客户端更新后，此项目自动更新失效了，LuaScripts项目那边国服只有sharecfgdata文件夹，其他服务器正常

### ISSUE THREAD

**Issue by yuelengqingchen** [AzurLaneTools/AzurLaneData#11]

**Comment by AutumnSun1996** [comment]
谢谢提醒。

已确认自动提取任务因内部代码的逻辑调整执行失败。
近期工作的事比较忙，这几周可能都没有太多时间进行修复，目前考虑先禁用国服的任务，之后有空了再慢慢处理。

**Comment by AutumnSun1996** [comment]
05-17 EN服也更新了，自动更新同样出现了错误。其他服务器估计也会陆续更新，我尽量在6月中旬前抽空处理吧

**Comment by AutumnSun1996** [comment]
修复完成，数据已更新至 8.1.X
