### ISSUE TITLE
请问是如何查询和提取script文件的？

### ISSUE THREAD

**Issue by kevinadol** [AzurLaneTools/AzurLaneData#2]
大佬你的另一个repo [AzurLaneLuaScripts](https://github.com/AzurLaneTools/AzurLaneLuaScripts) 应该是提取自script 32/64文件吧？你是如何提取这个script文件中的文件的？UABE是打不开的

**Comment by AutumnSun1996** [comment]
这个是我的博客，简单记录了一下实现流程。[碧蓝航线Lua代码和JSON数据提取方案](https://autumn21.top/hugo/2022-06-15/51831f8fea33/)

**Comment by MuteApo** [comment]
> 这个是我的博客，简单记录了一下实现流程。[碧蓝航线Lua代码和JSON数据提取方案](https://autumn21.top/hugo/2022-06-15/51831f8fea33/)

请问大佬能分享一下`sharecfgdata`下面文件的解析方法吗？uabdec和bcdec似乎不能正常工作
