### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Fernando2603** [AzurLaneTools/AzurLaneData#3]
Hi there, i noticed this file below missing some data in EN patch 6.2.188 (i only checked EN one, this should affected in other server folder as well)

[EN/ShareCfg/activity_task_permanent.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-3811979ac85b8a2befcf9f390c87c0b2aff42d312a71e27ad440fe9e8249a32a)
[EN/ShareCfg/benefit_buff_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-554a92076902251fa8d8e1eb3693e92e41862122034d53483fe47a74248c254f)
[EN/ShareCfg/box_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-fcfc396d58fe091dde58cb964bcf3adc3b3d19162a2d360ed56b50dffb24b909)
[EN/ShareCfg/expedition_data_by_map.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-e08e2fc705437f11b64d5fcfb9cdd0a80c55ac540ea51c68c3f22d363a203c88)
[EN/ShareCfg/furniture_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-dc096ee3e7424f3fda298528bb5f731c5520704bc739d452435643d5dc05cbb9)
[EN/ShareCfg/guild_base_event.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-1d37f500c633360a14a8623cc8f8eeccc420e0a498a86351060057d7eadbc5b1)
[EN/ShareCfg/item_medal_fetch.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-66c700e6b8ba7fb7cd925a6d7b552cf29e76a4ca323935082c6c2592d72882fd)
[EN/ShareCfg/memory_group.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-08dfd80155ca28e4b852a3483aac2e102808aec9be59524a70358a89f0b096d0)
[EN/ShareCfg/memory_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-e55abe47c06ba1df67a1d09d6f4dc0e3093a60575e92f6b913257f250b939241)
[EN/ShareCfg/pay_level_award.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-c2ab882448194e66443697ab12c8407d4465d538e5c928f33d01f5b2debabb45)
[EN/ShareCfg/ship_data_group.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-3e86a9dfc3584c4f9a4406a1a75aa1f897c49972c5a89a363a033cc216d295a6)
[EN/ShareCfg/ship_meta_breakout.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-bebd2ad128c3579e41d78aff1753c5b7d306637f51e8aa03e143ab4ee521e980)
[EN/ShareCfg/ship_skin_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-a4e4a58533a935a9df0315fcfed0b136cda1910a0898e363ba9591401ad02e27)
[EN/ShareCfg/ship_skin_words_add.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-42af855865b4c16280e868f20235c1e88c01810e3294c3d908dca03fca005cf5)
[EN/ShareCfg/ship_skin_words_extra.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-718ec5d2a1bc1b7081ca199f71d921b3aa1ef13e273a4dc51dd8f748df808f1f)
[EN/ShareCfg/shop_furniture_relation.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-428f069c04c3bf0b9c4f7bc8b7b3cdf95cf55834116fb086e993bf7f8ed18a7d)
[EN/ShareCfg/skill_data_display.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-cc05556c51b00e66718160c12e157348e769b9978d25107ec7ffb4b2ec74fd9b)
[EN/ShareCfg/skill_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-be45387049d1fa16c4bf4aa47b689b65363227111371443f29ad038bdd612b61)
[EN/ShareCfg/task_meta_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-19b51119f58032ad5ce5aa075ca26a36a1241403237baa13abc1c46d6d3de4cd)
[EN/ShareCfg/transform_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/commit/e16d2ab899c14ee5f7c7be0dcfc83345b0b9ef58#diff-3608781df8c3267662df42d7f649fdbf1a2eb3705d5705d6be1f2b87d08014dd)
etc.

the new file data only contains `__name` and `all` key or whatever in `pg.{filename}` in [AzurLaneLuaScripts](https://github.com/AzurLaneTools/AzurLaneLuaScripts)
```JSON
{
  "__name": "filename",
  "all": []
}
```

i assume this happened because in patch 6.2.88 the file got restructured so the data of listed id in `all` moved into `pg.data.{filename}`
and current extracted data from Lua only get data from `pg.{filename}`
```LUA
-- before
pg.{filename} = {
 [id]: { data },
 all: []
}
-- after
pg.{filename}= {
  _name: "filename",
  all: []
}
pg.data.{filename}= { data }
```

sorry for my bad english.
Thank you!

**Comment by AutumnSun1996** [comment]
Thanks for report.
I've already found the problem, but have not time to fix it now.
Should be able to find some time before next month, but no guarantees.

**Comment by AutumnSun1996** [comment]
As a temporary workaround, you can use lua scripts in [sharecfgdata folder of AzurLaneLuaScripts](https://github.com/AzurLaneTools/AzurLaneLuaScripts/tree/main/EN/sharecfgdata)

**Comment by ghost** [comment]
I wanted to follow up on this issue from 2 weeks ago and ask if we should expect a fix to the problem by this month or next month. If not this month, that's fine, though it would be great to receive a notice on this.

I also want to bring up that the parsing issue with the EN patch is also affecting .json data from the CN, JP, KR, and TW patches. Same files affected, just different regions.

Data from [EN/ShareCfg/activity_ins_language.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/activity_ins_language.json) is also not being parsed correctly, as an addition to the list of data files mentioned in the OP.
&#13;
&#13;
Thanks again for this repo. It's been a huge help for work and edits on the Azur Lane English Wiki.

**Comment by ETATomorrow** [comment]
It seems most of the data missing happened in the [region]/ShareCfg/. 

I tried to parse the files in [region]/ShareCfg/ and pushed them to [my repo](https://github.com/ETATomorrow/TempDataJSON). (I skipped word_template and word_legal_template)

I hope the files will be helpful while waiting for the repo to be fixed. 

AutumnSun, thank you for the repo.

**Comment by AutumnSun1996** [comment]
The extractor is updated to use `pg.base[target_name]` if available.
The changes seems to introduced some other issues, but at least missing data here is back now.
