### ISSUE TITLE
Some more missing data from recent update

### ISSUE THREAD

**Issue by ghost** [AzurLaneTools/AzurLaneData#5]
The recent update with commit `[update failed: [EN]: 6.2.238 -> 6.2.238]`(https://github.com/AzurLaneTools/AzurLaneData/commit/caacedc03d7b520317f176ab46ea6bcb5c019f5d) has resulted in more .json files missing data.

Here are the files from EN:
_I'm going to guess files from the CN, JP, KR, and TW repositories are also affected_

- [EN/ShareCfg/aircraft_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/bullet_template.json)
- [EN/ShareCfg/barrage_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/barrage_template.json)
- [EN/ShareCfg/bullet_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/bullet_template.json)
- [EN/ShareCfg/chapter_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/chapter_template.json)
- [EN/ShareCfg/chapter_template_loop.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/chapter_template_loop.json)
- [EN/ShareCfg/equip_data_statistics.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/equip_data_statistics.json)
- [EN/ShareCfg/equip_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/equip_data_template.json)
- [EN/ShareCfg/expedition_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/expedition_data_template.json)
- [EN/ShareCfg/ship_data_statistics.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/ship_data_statistics.json)
- [EN/ShareCfg/ship_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/ship_data_template.json)
- [EN/ShareCfg/ship_skin_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/ship_skin_template.json)
- [EN/ShareCfg/ship_skin_words.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/ship_skin_words.json)
- [EN/ShareCfg/shop_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/shop_template.json)
- [EN/ShareCfg/spweapon_data_statistics.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/spweapon_data_statistics.json)
- [EN/ShareCfg/task_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/task_data_template.json)
- [EN/ShareCfg/weapon_property.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/weapon_property.json)
- [EN/ShareCfg/world_chapter_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/world_chapter_template.json)
- [EN/ShareCfg/world_effect_data.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/world_effect_data.json)
- [EN/ShareCfg/world_event_data.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/world_event_data.json)

**Comment by AutumnSun1996** [comment]
All files except `ship_skin_template.json` here contains no useful data even before the update. The data is inside [sharecfgdata](https://github.com/AzurLaneTools/AzurLaneData/tree/main/EN/sharecfgdata).

<details>
<summary>content of aircraft_template</summary>

The content before the update is:
```js
{
  "__name": "aircraft_template",
  "all": [
    109,
    110,
    111,
    // ...
    3059512,
    3059513
  ]
}
```
and now it becomes empty list `[]`.
</details>


`ship_skin_template.json` requires some additional work, I'll try to fix it soon.

**Comment by AutumnSun1996** [comment]
`ship_skin_template.json` is back.
Thanks for your report.
