### ISSUE TITLE
Story no longer updates for JP client

### ISSUE THREAD

**Issue by KyouinDev** [AzurLaneTools/AzurLaneData#6]
[storyjp.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/JP/GameCfg/storyjp.json) has not been updated after [cecb542](https://github.com/AzurLaneTools/AzurLaneData/commit/cecb5426101ecdf734a96c0cb5b4c62637b83604) commit

**Comment by AutumnSun1996** [comment]
Thanks for report.
I was busy at work in recent weeks, and just got some time now.
Will try to fix it this weekend.
