### ISSUE TITLE
Juustagram data missing since Effulgence Before Eclipse event

### ISSUE THREAD

**Issue by ghost** [AzurLaneTools/AzurLaneData#7]
Since the [Effulgence Before Eclipse](https://azurlane.koumakan.jp/wiki/Effulgence_Before_Eclipse) event, data for Juustagrams have been missing:

- [activity_ins_language.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/activity_ins_language.json) - missing `"value"` data starting from `"ins_396"`.
- [activity_ins_npc_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/activity_ins_npc_template.json) - missing `"message_persist"`, `"npc_reply_persist"`, and `"time_persist"` data starting from `"3592"`.
- [activity_ins_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/ShareCfg/activity_ins_template.json) - missing `"message_persist"`, `"npc_discuss_persist"`, `"picture_persist"`, and `"time_persist"` data starting from `"396"`.

These three files update with the latest commits, but these specific keys are missing values.

I don't know if the game was updated so that this information is no longer found, but I held off on posting this issue believing information just wasn't being updated. But it's been two events now and Juustagram text has still yet to be updated, especially with this latest collaboration event with _Senran Kagura_.

**Comment by AutumnSun1996** [comment]
Previously it's from `ins_396`, and now it's from `ins_425`.
And they are also missing in the [lua file](https://github.com/AzurLaneTools/AzurLaneLuaScripts/blob/main/EN/sharecfg/activity_ins_language.lua)

I guess these missing data are fetched from server now after login, and will be filled after some time.
It's caused by the change of data fetch logic in game, I'm sorry but there is nothing I can do here.

**Comment by ghost** [comment]
Just wanted to re-open this ticket briefly to thank you for looking into this and responding. I'm aware that this specific data only updates with every new event, which sucks, but it is what it is.
