### ISSUE TITLE
dungeon.json 没有更新

### ISSUE THREAD

**Issue by iamxujian** [AzurLaneTools/AzurLaneData#8]
dungeon.json 看起来应该没有跟着 AzurLaneLuaScripts/CN/gamecfg/dungeon 一起更新。

不知道是不是出了什么 error 导致提交失败呢？

**Comment by AutumnSun1996** [comment]
这边近期的自动更新似乎因为存储空间不足或者其他原因失败了。已经清除了缓存，等重跑一下再看

**Comment by AutumnSun1996** [comment]
自动任务已修复
