### ISSUE TITLE
buffCfg.json not updated

### ISSUE THREAD

**Issue by Fernando2603** [AzurLaneTools/AzurLaneData#9]
buffCfg.json not updated also something wrong with ship_skin_template.json
![image](https://github.com/AzurLaneTools/AzurLaneData/assets/81207411/573e5939-acfd-4251-a86c-40331f4761f1)

**Comment by AutumnSun1996** [comment]
seems 'buff_17414' is missing, and cause the extractor to fail
just added some error handling logic, and hopefully it will be updated after next run

**Comment by AutumnSun1996** [comment]
problem fixed, buffCfg.json is updated as expected now
